name: Build and Upload nbanim Release to PyPI

on:
  release:
    types:
      - published

permissions:
  id-token: write  # Required for OIDC token permissions
  contents: read

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools setuptools-scm wheel twine check-manifest

      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          python -m build --sdist --wheel .

      - name: Check built artifacts
        run: |
          python -m twine check dist/*
          pwd
          if [ -f dist/nbanim-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist

  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.x"

      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist

      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist

  upload-to-pypi:
    needs: test-built-dist
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC token permissions
      contents: read

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
